version: '2'
services:
  mssql:
    build:
      context: .
      dockerfile: Dockerfile-mssql
    restart: always
    environment:
      - MSSQL_SA_PASSWORD=Msql12345678!
      - ACCEPT_EULA="Y"
  website:
    container_name: apache_php
    image: apache:php
    build:
      context: ./
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8000:80
    depends_on:
      - mssql