version: '2'
services:
  postgres:
    image: postgres:13.3
    container_name: postgres-server
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=myDB
    ports:
      - "5432:5432"
  website:
    container_name: apache_php
    image: apache:php
    build:
      context: ./
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8000:80
    depends_on:
      - postgres