version: '2'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-server
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=myDB
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
    ports:
      - "8082:3306"
  website:
    container_name: apache_php
    image: apache:php
    build:
      context: ./
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8000:80
    depends_on:
      - mysql